openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: API for managing contacts
tags:
  - name: Contacts
    description: Operations related to contacts
servers:
  - url: http://localhost:3000
paths:
  /contacts:
    get:
      tags:
        - Contacts
      summary: Get all contacts
      operationId: getContacts
      description: Retrieve all contacts.
      parameters:
        - name: type
          in: query
          description: Filter by contact type
          schema:
            type: string
      responses:
        200:
          description: List of contacts
        500:
          description: Internal server error
    post:
      tags:
        - Contacts
      summary: Create a contact
      operationId: createContact
      description: Create a new contact.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Contact'
      responses:
        201:
          description: Contact created
        400:
          description: Bad request
  /contacts/{contactId}:
    get:
      tags:
        - Contacts
      summary: Get contact by ID
      operationId: getContactById
      description: Retrieve a single contact by its ID.
      parameters:
        - name: contactId
          in: path
          required: true
          description: ID of the contact
          schema:
            type: string
      responses:
        200:
          description: Contact found
        404:
          description: Contact not found
    patch:
      tags:
        - Contacts
      summary: Update a contact
      operationId: updateContact
      description: Update a contact by ID.
      parameters:
        - name: contactId
          in: path
          required: true
          description: ID of the contact
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Contact'
      responses:
        200:
          description: Contact updated
        400:
          description: Bad request
    delete:
      tags:
        - Contacts
      summary: Delete a contact
      operationId: deleteContact
      description: Delete a contact by ID.
      parameters:
        - name: contactId
          in: path
          required: true
          description: ID of the contact
          schema:
            type: string
      responses:
        204:
          description: Contact deleted
        404:
          description: Contact not found
components:
  schemas:
    Contact:
      type: object
      properties:
        name:
          type: string
        phoneNumber:
          type: string
        email:
          type: string
        contactType:
          type: string
          enum:
            - work
            - home
            - personal
